### ISSUE TITLE
Misplaced brackets cause error in Knockout Round simulation

### ISSUE THREAD

**Issue by bkktimber** [lbenz730/intl_soccer_2024#3]
## Issue

There are misplaced brackets in `euro_sim.R` and `copa_sim.R`, which cause errors when each is run.

```
Error in (function (.x, .f, ..., .progress = FALSE)  : 
  ℹ In index: 1.
Caused by error in `filter()`:
! We detected a named input.
ℹ This usually means that you've used `=` instead of `==`.
ℹ Did you mean `.id == "sim_id"`?
```

## Solution
Rearrange brackets in both files.

**Comment by lbenz730** [comment]
Thanks for this alert, i actually caught it myself and it should be fixed in latest file versions.
